### ISSUE TITLE
create external server for kinect data

### ISSUE THREAD

**Issue by bjpritch** [mwcz/Kimotion#15]
A server needs to be set up to run fakenect data, so users can collaborate without the requirement of a kinect.

The server should be able to easily integrate with a running kimotion client (by setting the server:port in the startup config).

**Comment by mwcz** [comment]
With recordings, we shouldn't need this anymore.  Still need some way to publish recordings after sparkcon, so people can just visit (for example) kimotion.xyz/live and see live mods.
