### ISSUE TITLE
server doesn't send data to all connected clients

### ISSUE THREAD

**Issue by mwcz** [mwcz/Kimotion#19]
When more than one clients connect to the server, only the most recent one will get data.  The server emits this:

```
Could not claim interface on camera: -6
Failed to open camera subdevice or it is not disabled.Failed to open motor subddevice or it is not disabled.Failed to open audio subdevice or it is not disabled.Error: Can't open device. 1.) is it plugged in? 2.) Read the README
```

And stops sending data to previous clients.

**Comment by philosophe** [comment]
See branch multiple_client_server

In the new configuration, all websocket server instances would reference a single thread running the freenect loop.  Each new InputServer registers itself as an observer of the kinect loop (see input.KinectSubject).  Each time the KinectSubject receives new depth data, it notifies each observer of the new depth value.  The InputServer then sends the depth data to its client.
