### ISSUE TITLE
improve prompt to choose recording or websocket data source

### ISSUE THREAD

**Issue by mwcz** [mwcz/Kimotion#39]
Right now it's a dumb `confirm` box that doesn't really make sense.

![screenshot from 2015-09-27 21-20-03](https://cloud.githubusercontent.com/assets/364615/10126300/8bb6ec18-655d-11e5-80ab-ef20d30c69d1.png)

It should instead display a popup that allows for choosing between a list of recordings or a live server w/ URL.  Something like this:

![screenshot from 2015-09-27 21-40-33](https://cloud.githubusercontent.com/assets/364615/10126436/73c6b400-6560-11e5-8852-5746aaac87fe.png)

**Comment by Jared-Sprague** [comment]
Yeah that's a lot easier to understand!

**Comment by mwcz** [comment]
Accomplished by allowing mods to select their own input source.
