### ISSUE TITLE
The kinect server is not starting

### ISSUE THREAD

**Issue by dortamiguel** [mwcz/Kimotion#42]
I installed all the dependencies in macos sierra.

But when I do "python server.py" it doesn't complain but when I go to the application it doesn't appear anything.

Wat can it be?

**Comment by mwcz** [comment]
Hmm, that's a good question.  Would you mind taking a screenshot of the application and sharing it here?  Bonus points if you could take a screenshot with the JavaScript console open!

**Comment by dortamiguel** [comment]
Here it is!

![image](https://cloud.githubusercontent.com/assets/3449006/19921761/4f1d8e0e-a0d7-11e6-903b-8f20844f44b5.png)

**Comment by mwcz** [comment]
Thanks!  I see the problem, it's trying to load a kinect recording instead of using the real kinect.  Uncheck the "use recording" checkbox and it should start using your Kinect!

**Comment by mwcz** [comment]
I should add that _sometimes_ server.py needs to be restarted once or twice, I'm not sure why. :confused:

**Comment by dortamiguel** [comment]
Awesome!! now it works perfectly 😊

**Comment by mwcz** [comment]
Woohoo!!!  Let me know if I can help with anything else!
