### ISSUE TITLE
The xbox one kinect works with this project?

### ISSUE THREAD

**Issue by dortamiguel** [mwcz/Kimotion#43]
Just that question 😅

**Comment by mwcz** [comment]
I haven't tested it myself, but I'm almost positive it won't work.  I'm using libfreenect which supports the original Kinect.  I do think there's an updated version of libfreenect that works with the XBox One kinect, but I haven't tried it.  Pull requests welcome!!!

**Comment by mwcz** [comment]
I'm closing this issue but if you do try getting it to work, feel free to reopen it or start a new issue.  I'd be happy to help.
